# -*- coding: utf-8 -*-
"""LLMVideoWithText.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzizWZRjkHTkvtnFcRAZPgOXQyUCFdWL
"""

from modelscope.pipelines import pipeline
from modelscope.outputs import OutputKeys

p = pipeline('text-to-video-synthesis', 'damo/text-to-video-synthesis')

test_text = {
        'text': 'virat kohli as lord ram',
    }
output_video_path = p(test_text,)[OutputKeys.OUTPUT_VIDEO]
print('output_video_path:', output_video_path)

import gdown

"""###  Here we can get the Output for our prompts"""

import google.colab.files as files
files.download("/tmp/tmplox8lxyd.mp4")

